export const USER_SIGNIN = 'USER_SIGNIN' // 登录成功

export const USER_SIGNOUT = 'USER_SIGNOUT' // 退出登录

export const UPDATE_USER_COIN = 'UPDATE_USER_COIN'	//更新用户玩家

export const SHOW_PLAYER_DETAILS = 'SHOW_PLAYER_DETAILS'   //查看玩家信息，伪请求

export const GET_PLAYER_DETAILS_HISTORY_SUCCESS = 'GET_PLAYER_DETAILS_HISTORY_SUCCESS'  //获取玩家行为数据成功

export const GET_PLAYER_DETAILS_HISTORY_FAIL = 'GET_PLAYER_DETAILS_HISTORY_FAIL'				//获取玩家行为数据失败

export const REQUEST_PLAYER_DETAILS_HISTORY = 'REQUEST_PLAYER_DETAILS_HISTORY'				//获取玩家行为数据失败

export const REQUEST_ROOM_LIST = 'REQUEST_ROOM_LIST'				//获取房间行为数据失败

export const GET_ROOM_LIST_FAIL = 'GET_ROOM_LIST_FAIL'				//获取房间行为数据失败

export const GET_ROOM_LIST_SUCCESS = 'GET_ROOM_LIST_SUCCESS'				//获取房间行为数据失败
 
export const REQUEST_APPLY_FINSH = 'REQUEST_APPLY_FINSH'				//请求

export const REQUEST_ORDER_LIST = 'REQUEST_ORDER_LIST'				//请求Order

export const GET_ORDER_LIST_FAIL = 'GET_ORDER_LIST_FAIL'				//请求Order

export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS'				//请求

export const REQUEST_APPLY_LIST = 'REQUEST_APPLY_LIST'				//请求

export const GET_APPLY_LIST_FAIL = 'GET_APPLY_LIST_FAIL'				//请求

export const GET_APPLY_LIST_SUCCESS = 'GET_APPLY_LIST_SUCCESS'				//请求

export const REQUEST_APPLY = 'REQUEST_APPLY'				//请求

export const SET_PLAYER_ID = 'SET_PLAYER_ID'				//请求

export const GET_PLAYER_DETAILS_ORDER_SUCCESS = 'GET_PLAYER_DETAILS_ORDER_SUCCESS'				//请求

export const GET_PLAYER_DETAILS_ORDER_FAIL = 'GET_PLAYER_DETAILS_ORDER_FAIL'				//请求


export const GET_PLAYER_FAILD = 'GET_PLAYER_FAILD'				//请求

export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS'				//请求

export const FINSH_REQUEST = 'FINSH_REQUEST'				//请求finsh




export const GET_LINK_LIST_SUCCESS = 'GET_LINK_LIST_SUCCESS'
export const GET_LINK_LIST_FAILD = 'GET_LINK_LIST_FAILD'
export const REQUEST_LINK_LIST = 'REQUEST_LINK_LIST'

export const GET_SELLER_LIST_SUCCESS = 'GET_SELLER_LIST_SUCCESS'
export const GET_SELLER_LIST_FAILD = 'GET_SELLER_LIST_FAILD'
export const REQUEST_SELLER_LIST = 'REQUEST_SELLER_LIST'

export const GET_PLAYER_LIST_SUCCESS = 'GET_PLAYER_LIST_SUCCESS'
export const GET_PLAYER_LIST_FAILD = 'GET_PLAYER_LIST_FAILD'
export const REQUEST_PLAYER_LIST = 'REQUEST_PLAYER_LIST'

export const GET_ADMIN_INFO_SUCCESS = 'GET_ADMIN_INFO_SUCCESS'
export const GET_ADMIN_INFO_FAILD = 'GET_ADMIN_INFO_FAILD'
export const REQUEST_ADMIN_INFO = 'REQUEST_ADMIN_INFO'

export const GET_SELLER_INFO_SUCCESS = 'GET_SELLER_INFO_SUCCESS'
export const GET_SELLER_INFO_FAILD = 'GET_SELLER_INFO_FAILD'
export const REQUEST_SELLER_INFO = 'REQUEST_SELLER_INFO'

export const GET_SELLER_DETAILS_SUCCESS = 'GET_SELLER_DETAILS_SUCCESS'
export const GET_SELLER_DETAILS_FAILD = 'GET_SELLER_DETAILS_FAILD'
export const REQUEST_SELLER_DETAILS = 'REQUEST_SELLER_DETAILS'
export const UPDATE_SELLER_DETAILS_COIN = 'UPDATE_SELLER_DETAILS_COIN'

export const GET_PLAYER_DETAILS_SUCCESS = 'GET_PLAYER_DETAILS_SUCCESS'

export const GET_PLAYER_DETAILS_FAILD = 'GET_PLAYER_DETAILS_FAILD'

export const REQUEST_PLAYER_DETAILS = 'REQUEST_PLAYER_DETAILS'



